import { Category, Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Basmati Rice (XL Grain)',
    category: Category.RICE,
    description: 'Aged extra long grain basmati rice, perfect for biryani.',
    priceMRP: 120,
    priceWholesale: 85,
    minOrderQty: 25,
    unit: 'kg',
    image: 'https://picsum.photos/400/400?random=1',
    inStock: true,
  },
  {
    id: '2',
    name: 'Sonam Masoori Rice',
    category: Category.RICE,
    description: 'High quality daily use medium grain rice.',
    priceMRP: 60,
    priceWholesale: 42,
    minOrderQty: 50,
    unit: 'kg',
    image: 'https://picsum.photos/400/400?random=2',
    inStock: true,
  },
  {
    id: '3',
    name: 'Tur Dal (Polished)',
    category: Category.PULSES,
    description: 'Premium quality polished Toor Dal.',
    priceMRP: 140,
    priceWholesale: 115,
    minOrderQty: 10,
    unit: 'kg',
    image: 'https://picsum.photos/400/400?random=3',
    inStock: true,
  },
  {
    id: '4',
    name: 'Sunflower Oil (15L Tin)',
    category: Category.OILS,
    description: 'Refined sunflower oil, bulk tin packaging.',
    priceMRP: 1800,
    priceWholesale: 1550,
    minOrderQty: 5,
    unit: 'tin',
    image: 'https://picsum.photos/400/400?random=4',
    inStock: true,
  },
  {
    id: '5',
    name: 'Everest Chicken Masala',
    category: Category.SPICES,
    description: 'Bulk pack of chicken masala blend.',
    priceMRP: 80,
    priceWholesale: 62,
    minOrderQty: 20,
    unit: 'pack (100g)',
    image: 'https://picsum.photos/400/400?random=5',
    inStock: true,
  },
  {
    id: '6',
    name: 'Kashmiri Red Chilli Powder',
    category: Category.SPICES,
    description: 'Vibrant color, medium heat.',
    priceMRP: 450,
    priceWholesale: 320,
    minOrderQty: 5,
    unit: 'kg',
    image: 'https://picsum.photos/400/400?random=6',
    inStock: true,
  },
  {
    id: '7',
    name: 'Soy Sauce (Dark)',
    category: Category.SAUCES,
    description: 'Restaurant grade dark soy sauce.',
    priceMRP: 120,
    priceWholesale: 85,
    minOrderQty: 12,
    unit: 'bottle (750ml)',
    image: 'https://picsum.photos/400/400?random=7',
    inStock: true,
  },
  {
    id: '8',
    name: 'Green Chilli Sauce',
    category: Category.SAUCES,
    description: 'Spicy green chilli sauce for fast food.',
    priceMRP: 90,
    priceWholesale: 65,
    minOrderQty: 12,
    unit: 'bottle (750ml)',
    image: 'https://picsum.photos/400/400?random=8',
    inStock: true,
  },
  {
    id: '9',
    name: 'Moong Dal (Yellow)',
    category: Category.PULSES,
    description: 'Split yellow moong beans.',
    priceMRP: 110,
    priceWholesale: 88,
    minOrderQty: 10,
    unit: 'kg',
    image: 'https://picsum.photos/400/400?random=9',
    inStock: true,
  }
];

export const MARKET_TRENDS = [
  { month: 'Jan', Rice: 40, Oil: 140, Pulses: 100 },
  { month: 'Feb', Rice: 41, Oil: 138, Pulses: 105 },
  { month: 'Mar', Rice: 42, Oil: 142, Pulses: 102 },
  { month: 'Apr', Rice: 41, Oil: 145, Pulses: 108 },
  { month: 'May', Rice: 43, Oil: 150, Pulses: 110 },
  { month: 'Jun', Rice: 42, Oil: 155, Pulses: 115 },
];
